"""3-pillar integration material vehicle subjects individual logins

Revision ID: 6712205c0fea
Revises: 91ac8d9e199f
Create Date: 2026-07-05 10:15:34.922226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6712205c0fea'
down_revision: Union[str, None] = '91ac8d9e199f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('rc_valid', sa.Boolean(), nullable=False),
    sa.Column('puc_valid', sa.Boolean(), nullable=False),
    sa.Column('fitness_valid', sa.Boolean(), nullable=False),
    sa.Column('adp_driver', sa.String(length=128), nullable=True),
    sa.Column('rfid_tag', sa.String(length=64), nullable=True),
    sa.Column('vep_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('tool_category', sa.String(length=8), nullable=True),
    sa.Column('carried_by_individual_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['carried_by_individual_id'], ['individuals.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Batch mode so SQLite can add FKs and relax NOT NULL. Server defaults are
    # required by SQLite when adding NOT NULL columns.
    with op.batch_alter_table('applications') as batch:
        batch.add_column(sa.Column('pillar', sa.Enum('man', 'material', 'vehicle', name='pillar'),
                                   nullable=False, server_default='man'))
        batch.add_column(sa.Column('pass_type', sa.String(length=16), nullable=True))
        batch.add_column(sa.Column('material_item_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch.alter_column('individual_id', existing_type=sa.INTEGER(), nullable=True)
        batch.create_foreign_key('fk_applications_vehicle', 'vehicles', ['vehicle_id'], ['id'])
        batch.create_foreign_key('fk_applications_material', 'material_items', ['material_item_id'], ['id'])

    with op.batch_alter_table('individuals') as batch:
        batch.add_column(sa.Column('login_authorized', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('users') as batch:
        batch.add_column(sa.Column('individual_id', sa.Integer(), nullable=True))
        batch.create_foreign_key('fk_users_individual', 'individuals', ['individual_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('users') as batch:
        batch.drop_constraint('fk_users_individual', type_='foreignkey')
        batch.drop_column('individual_id')
    with op.batch_alter_table('individuals') as batch:
        batch.drop_column('login_authorized')
    with op.batch_alter_table('applications') as batch:
        batch.drop_constraint('fk_applications_material', type_='foreignkey')
        batch.drop_constraint('fk_applications_vehicle', type_='foreignkey')
        batch.alter_column('individual_id', existing_type=sa.INTEGER(), nullable=False)
        batch.drop_column('vehicle_id')
        batch.drop_column('material_item_id')
        batch.drop_column('pass_type')
        batch.drop_column('pillar')
    op.drop_table('material_items')
    op.drop_table('vehicles')
